### PR TITLE
Add 6th level TLDs.

### PR DESCRIPTION
**Pull request by jbaggs**
Hey Seth. Looks like Amazon has bumped us up to 6th level TLDs.

### CODE REVIEW

**Comment by jbaggs** [comment]
Something I was thinking about when looking at `main.zeek`:  I don't know what the time cost is on each regex match, but does it make sense to reverse the match order in the `effective_tld`, `effective_domain`, and `effective_subdomain` functions since the domains are statistically more likely to match at the lower depths?

**Comment by jbaggs** [comment]
While we're at it, I added IDNs to tld-data.zeek. Neither of our prior scripts for converting the public suffix list were dealing with text that wasn't ascii, so I added in utf-8 to punycode to cover the domains we had been missing.

**Comment by sethhall** [comment]
> Something I was thinking about when looking at `main.zeek`: I don't know what the time cost is on each regex match, but does it make sense to reverse the match order in the `effective_tld`, `effective_domain`, and `effective_subdomain` functions since the domains are statistically more likely to match at the lower depths?

I don't immediately have a good sense if that'd be helpful or not.  Generally regular expressions in zeek are pretty inexpensive, but it does end up doing more string scanning.  If you were interested in doing some performance improvements you could look into using a paraglob (it's already built into zeek!)... https://github.com/zeek/paraglob#inside-zeek

**Comment by jbaggs** [comment]
Ah, thanks. I'll take a look at it.

**Pull request merged**
